### ISSUE TITLE
Availability date

### ISSUE THREAD

**Issue by JEDIBC** [micronaut-projects/micronaut-jackson-xml#1]
Hi,

I'm really interested in this project as I need to produce XML output on my Rest application.

Is there a planned release date ? How can I test it without manually copying your files in my project ?

Thanks

Regards,

Bruno

**Comment by graemerocher** [comment]
Will be released with Micronaut 1.3 RC1 today

**Comment by JEDIBC** [comment]
That's great ! Thank you for your work !
