### ISSUE TITLE
Jackson XmL wrapper validation action fails

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-jackson-xml#284]
### Issue description

see https://github.com/micronaut-projects/micronaut-jackson-xml/actions/runs/5309751959/jobs/9610818154

**Comment by timyates** [comment]
Looks like this is a known (but seemingly ignored) issue with the wrapper-validation-action

https://github.com/gradle/wrapper-validation-action/issues/69

**Comment by timyates** [comment]
My recommendation for now would be to try re-running the action
