### ISSUE TITLE
Improve Documentation with samples of HTTP Declarative client consuming XML

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-jackson-xml#49]
The documentation, right now, is sparse. We should provide documentation about:

- [ ] The ability to have a Micronaut declarative HTTP Client to consume a XML API. 
- [ ] The ability of a controller to consume a XML request.  

It should have a structure `test-suite`, `test-suite-groovy`, `test-suite-kotlin`, see [security module](https://github.com/micronaut-projects/micronaut-security) as a repository structure, to use three language snippets. 

Maybe we can use https://github.com/sdelamo/eurorates repository POJOs. Those POJOs show how to use xml attributes, xml spec etc.

**Comment by bruno-lopes** [comment]
I'm trying exactly this, but I have no idea how to consume XML with HTTP declarative client.
